services:

  MediaWiki\OAuthClient\Client:
    factory: [ 'MediaWiki\OAuthClient\Client', newFromKeyAndSecret ]
    arguments:
      - '%toolforge.oauth.url%'
      - '%toolforge.oauth.consumer_key%'
      - '%toolforge.oauth.consumer_secret%'

  Wikimedia\ToolforgeBundle\Controller\AuthController:
    tags: [ 'controller.service_arguments' ]
    autoconfigure: true
    autowire: true

  # Intuition i18n library.
  # The service class is a subclass of Intuition.
  Krinkle\Intuition\Intuition:
    factory: ['Wikimedia\ToolforgeBundle\Service\Intuition', serviceFactory]
    arguments:
      - "@request_stack"
      - "@session"
      - "%kernel.root_dir%"
      - "%toolforge.intuition.domain%"

  Wikimedia\ToolforgeBundle\Logger\WebRequestProcessor:
    tags: { name: monolog.processor }
    autowire: true

  Wikimedia\ToolforgeBundle\Service\NativeSessionStorage:
    arguments:
      $options: '%session.storage.options%'
      $handler: '@session.handler'
      $metaBag: '@session.storage.metadata_bag'
      $requestStack: '@request_stack'

  Wikimedia\ToolforgeBundle\Twig\Extension:
    arguments:
      - '@Krinkle\Intuition\Intuition'
      - "@session"
      - "%toolforge.intuition.domain%"
    tags: [ "twig.extension" ]
