services:

  MediaWiki\OAuthClient\Client:
    factory: [ 'MediaWiki\OAuthClient\Client', newFromKeyAndSecret ]
    arguments:
      - 'https://meta.wikimedia.org/w/index.php?title=Special:OAuth'
      - '%toolforge.oauth.consumer_key%'
      - '%toolforge.oauth.consumer_secret%'

  Wikimedia\ToolforgeBundle\Controller\AuthController:
    tags: [ 'controller.service_arguments' ]

  # Intuition i18n library.
  # The service class is a subclass of Intuition.
  Krinkle\Intuition\Intuition:
    factory: ['Wikimedia\ToolforgeBundle\Service\Intuition', serviceFactory]
    arguments: ["@request_stack", "@session", "%kernel.root_dir%", "%toolforge.intuition.domain%"]

  Wikimedia\ToolforgeBundle\Twig\Extension:
    arguments:
      - '@Krinkle\Intuition\Intuition'
      - "%kernel.root_dir%"
      - "%toolforge.intuition.domain%"
    tags: [ "twig.extension" ]
